site_name: Karl Barth-Gesamtausgabe Dokumentation
theme:
  name: material
  palette:
    primary: light blue
    accent: blue
  font:
    text: Roboto
  logo: images/logo.png
  language: de
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.path
    - navigation.indexes
    - navigation.footer
extra_css:
  - style.css
plugins:
  - render_swagger
  - search:
      lang:
        - de 
        - en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
      enable_creation_date: true
  #- markdown-exec
  # since we are nt a sponsor:
  #- git-committers:
  #    repository: Karl-Barth/kb-dokumentation
  #    branch: main
  #- git-authors
markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://social.anoxinon.de/@anton
copyright: "&copy; 2023–2026 Karl Barth-Archiv"
repo_url: https://github.com/Karl-Barth/kb-dokumentation
repo_name: Karl-Barth/kb-dokumentation
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Textstruktur:
    - Gliederung: textstruktur/gliederung.md
    - Überschriften: textstruktur/ueberschriften.md
    - Absatz: textstruktur/absatz.md
    - Gedichte: textstruktur/gedichte.md
    - Unterschriften: textstruktur/unterschriften.md
    - Datum mit Ortsangabe: textstruktur/dateline.md
    - Listen: textstruktur/listen.md
    - Tabellen: textstruktur/tabellen.md
    - Wörtliche Rede: textstruktur/woertliche-rede.md
    - Bilder: textstruktur/bilder.md
    - Anmerkungen: textstruktur/anmerkungen.md
    - Seitenanfang: textstruktur/seitenanfang.md
    - Zeilenumbruch: textstruktur/zeilenumbruch.md
  - Textelemente:
    - Datumsangaben: textelemente/datumsangaben.md
    - Akteure: textelemente/akteure.md
    - Orte: textelemente/orte.md
    - Lieder: textelemente/lieder.md
    - Literatur: textelemente/literatur.md
    - Bibelstellen: textelemente/bibelstellen.md
    - Hervorhebungen: textelemente/hervorhebungen.md
    - Korrekturen der Druckausgabe: textelemente/korrekturen-der-druckausgabe.md
    - Editorische Ergänzungen: textelemente/editorische-ergaenzungen.md
    - Fremdsprache: textelemente/fremdsprache.md
    - Querverweise und Links: textelemente/querverweise.md
  - Datenbank:
    - Texte: datenbank/texte.md
    - Akteure: datenbank/akteure.md
    - Lieder: datenbank/lieder.md
    - Literatur: datenbank/literatur.md
    - Orte: datenbank/orte.md
  - Textsorten:
    - Predigten: textsorten/predigten.md
    - Briefe: textsorten/briefe.md
    - Vorlesungsreihen: textsorten/vorlesungsreihen.md
    - Vorträge: textsorten/vortraege.md
  - Abkürzungen: abkuerzungen.md
  - Bibelbücher: bibel.md
  #- Workflow:  # verschoben ins Wiki
  #  - Synchronisierung von Daten ins KBA: workflow/sync_kba.md
  #  - Datenbankinkonsistenzen: workflow/inkonsistenzen.md
  - Tag-Library:
    - tag-library/index.md
    - TEI: tag-library/TEI.md
    - ab: tag-library/ab.md
    - abbr: tag-library/abbr.md
    - addrLine: tag-library/addrLine.md
    - address: tag-library/address.md
    - altIdentifier: tag-library/altIdentifier.md
    - anchor: tag-library/anchor.md
    - argument: tag-library/argument.md
    - author: tag-library/author.md
    - availability: tag-library/availability.md
    - bibl: tag-library/bibl.md
    - biblScope: tag-library/biblScope.md
    - body: tag-library/body.md
    - cell: tag-library/cell.md
    - change: tag-library/change.md
    - choice: tag-library/choice.md
    - cit: tag-library/cit.md
    - closer: tag-library/closer.md
    - corr: tag-library/corr.md
    - correspAction: tag-library/correspAction.md
    - correspContext: tag-library/correspContext.md
    - correspDesc: tag-library/correspDesc.md
    - creation: tag-library/creation.md
    - date: tag-library/date.md
    - dateline: tag-library/dateline.md
    - div: tag-library/div.md
    - docDate: tag-library/docDate.md
    - edition: tag-library/edition.md
    - editionStmt: tag-library/editionStmt.md
    - editor: tag-library/editor.md
    - encodingDesc: tag-library/encodingDesc.md
    - epigraph: tag-library/epigraph.md
    - event: tag-library/event.md
    - figDesc: tag-library/figDesc.md
    - figure: tag-library/figure.md
    - fileDesc: tag-library/fileDesc.md
    - foreign: tag-library/foreign.md
    - graphic: tag-library/graphic.md
    - head: tag-library/head.md
    - hi: tag-library/hi.md
    - idno: tag-library/idno.md
    - item: tag-library/item.md
    - keywords: tag-library/keywords.md
    - l: tag-library/l.md
    - langUsage: tag-library/langUsage.md
    - language: tag-library/language.md
    - lb: tag-library/lb.md
    - lg: tag-library/lg.md
    - licence: tag-library/licence.md
    - list: tag-library/list.md
    - listBibl: tag-library/listBibl.md
    - listEvent: tag-library/listEvent.md
    - listPrefixDef: tag-library/listPrefixDef.md
    - metamark: tag-library/metamark.md
    - milestone: tag-library/milestone.md
    - msContents: tag-library/msContents.md
    - msDesc: tag-library/msDesc.md
    - msIdentifier: tag-library/msIdentifier.md
    - msItem: tag-library/msItem.md
    - note: tag-library/note.md
    - opener: tag-library/opener.md
    - orgName: tag-library/orgName.md
    - p: tag-library/p.md
    - pb: tag-library/pb.md
    - persName: tag-library/persName.md
    - placeName: tag-library/placeName.md
    - postscript: tag-library/postscript.md
    - prefixDef: tag-library/prefixDef.md
    - profileDesc: tag-library/profileDesc.md
    - ptr: tag-library/ptr.md
    - pubPlace: tag-library/pubPlace.md
    - publicationStmt: tag-library/publicationStmt.md
    - publisher: tag-library/publisher.md
    - q: tag-library/q.md
    - quote: tag-library/quote.md
    - ref: tag-library/ref.md
    - repository: tag-library/repository.md
    - revisionDesc: tag-library/revisionDesc.md
    - row: tag-library/row.md
    - rs: tag-library/rs.md
    - salute: tag-library/salute.md
    - seg: tag-library/seg.md
    - sic: tag-library/sic.md
    - signed: tag-library/signed.md
    - sourceDesc: tag-library/sourceDesc.md
    - sp: tag-library/sp.md
    - span: tag-library/span.md
    - speaker: tag-library/speaker.md
    - sponsor: tag-library/sponsor.md
    - stage: tag-library/stage.md
    - table: tag-library/table.md
    - teiHeader: tag-library/teiHeader.md
    - term: tag-library/term.md
    - text: tag-library/text.md
    - textClass: tag-library/textClass.md
    - title: tag-library/title.md
    - titleStmt: tag-library/titleStmt.md
  - API: api/index.md
  
