site_name: Karl Barth-Gesamtausgabe Dokumentation
theme:
  name: material
  palette:
    primary: light blue
    accent: blue
  font:
    text: Roboto
  logo: images/logo.png
  language: de
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.path
    #- navigation.indexes
    - navigation.footer
extra_css:
  - style.css
plugins:
  - render_swagger
  - search:
      lang:
        - de 
        - en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
      enable_creation_date: true
  #- markdown-exec
  # since we are nt a sponsor:
  #- git-committers:
  #    repository: Karl-Barth/kb-dokumentation
  #    branch: main
  #- git-authors
markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://social.anoxinon.de/@anton
repo_url: https://github.com/Karl-Barth/kb-dokumentation
repo_name: Karl-Barth/kb-dokumentation
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Textstruktur:
    - Gliederung: textstruktur/gliederung.md
    - Überschriften: textstruktur/ueberschriften.md
    - Absatz: textstruktur/absatz.md
    - Unterschriften: textstruktur/unterschriften.md
    - Anmerkungen: textstruktur/anmerkungen.md
    - Seitenanfang: textstruktur/seitenanfang.md
    - Zeilenumbruch: textstruktur/zeilenumbruch.md
  - Textelemente:
    - Datumsangaben: textelemente/datumsangaben.md
  - Datenbank:
    - Texte: datenbank/texte.md
    - Akteure: datenbank/akteure.md
    - Lieder: datenbank/lieder.md
    - Literatur: datenbank/literatur.md
    - Orte: datenbank/orte.md
  - Abkürzungen: abkuerzungen.md
  - Bibelbücher: bibel.md
  - Workflow: 
    - Synchronisierung von Daten ins KBA: workflow/sync_kba.md
    #- Metadatenbank: workflow/metadatenbank.md
    - Datenbankinkonsistenzen: workflow/inkonsistenzen.md
  - API: api/index.md
  
